### ISSUE TITLE
[BUG] failed to build in net6 preview7

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#19]
I think the path of StaticWebAssets.xml has been changed in the new SDK version.
Instead of in the `obj\Debug\net6.0\staticwebassets` folder, it belongs directly `obj\Debug\net6.0` now
```
  Blazor.BrowserExtension.Build.targets(218, 5): [MSB4018] The "BlazorToBrowserExtensionProcessStaticWebAssetsManifest" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'C:\Repos\newbe\Amazing-Favorites\src\Newbe.BookmarkManager\obj\Debug\net6.0\staticwebassets\Newbe.BookmarkManager.StaticWebAssets.xml'.
File name: 'C:\Repos\newbe\Amazing-Favorites\src\Newbe.BookmarkManager\obj\Debug\net6.0\staticwebassets\Newbe.BookmarkManager.StaticWebAssets.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in System.Private.CoreLib.dll:token 0x6000126+0xbb
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6000125+0x48
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x600631c+0x78
   at Blazor.BrowserExtension.Build.Tasks.BlazorToBrowserExtensionProcessStaticWebAssetsManifest.Execute() in Blazor.BrowserExtension.Build.dll:token 0x6000029+0x65
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x6001602+0x3e
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x6001481+0x804
```
<img width="632" alt="explorer_EpuMFUDQYN" src="https://user-images.githubusercontent.com/7685462/129447382-1500ba49-8da1-4ba5-bf6a-686964381da5.png">

**Comment by newbe36524** [comment]
And it is empty 
<img width="598" alt="explorer_IenmbRQc3D" src="https://user-images.githubusercontent.com/7685462/129447439-804ca00c-522d-40df-9e90-065fd6a673a3.png">

**Comment by mingyaulee** [comment]
Yes indeed there has been some changes in preview 7 that is significantly different with the build and publishing process. I will need to spend some time to review the build process to maintain compatibility with .net 5 too.

**Comment by mingyaulee** [comment]
It should be fixed in v0.5.2

**Comment by newbe36524** [comment]
But I think it still fail if only upgrade this package to 0.5.2
https://github.com/newbe36524/Amazing-Favorites/pull/109/checks?check_run_id=3347279773

**Comment by mingyaulee** [comment]
Yeah the latest version does not work with preview 6 but it will work with preview 7

**Comment by newbe36524** [comment]
it is ok to build, but fail to valid hash 
I load extension from browserextension folder
![image](https://user-images.githubusercontent.com/7685462/129823109-859898d9-03cf-41c7-a508-0edd8b4d3468.png)

**Comment by newbe36524** [comment]
it works after update manifest.json
```
'sha256-SQC3opwSNRzP3qBB9CWB9I3347XafmEdFyNx7sU8EhI=' 'sha256-ekPKVeJX0sFL97OO7iucY3R3j3qdTIvUSwffdbcbxjA=' 'sha256-Ku0DBFoNk825E3GZZ7OLqYiLPXgpfFVkmlpLYzy52Q0=' 'sha256-RXfkN4imQn+87yqYyEUBoeMJmcNRWSMfgv80LKZxKbc='
```

**Comment by mingyaulee** [comment]
That is odd, it seems to be working just fine for me in Chrome after I build it. Can you provide the steps to reproduce?

**Comment by newbe36524** [comment]
I cannot provide the steps to reproduce, and it works even I remove the hashes.
I guess there is some problem when I just switch the preview version between 6  and 7 without clean up obj and bin folder.
In any case, everything is fine now.
